// Run via `npm run record-prices` after any manual price-verification pass over
// lib/data/parts.ts. Records today's price for every part currently in the catalog and prunes
// any history entry older than 30 days, so lib/data/priceHistory.ts stays a rolling 30-day
// window of what's actually been checked — not a permanent archive, and not something that
// prunes itself on a schedule: it only updates when this script runs.
import { writeFileSync } from "node:fs";
import { allParts } from "../lib/data/parts";
import { priceHistory as existingHistory } from "../lib/data/priceHistory";
import type { PriceCheck } from "../lib/types";

const THIRTY_DAYS_MS = 30 * 24 * 60 * 60 * 1000;
const today = new Date().toISOString().slice(0, 10);
const cutoff = Date.now() - THIRTY_DAYS_MS;

const newChecks: PriceCheck[] = allParts.map((p) => ({ partId: p.id, price: p.price, checkedAt: today }));

// Drop anything past the 30-day window, and drop today's old entries so re-running the script
// same-day replaces rather than duplicates.
const kept = existingHistory.filter((c) => new Date(c.checkedAt).getTime() >= cutoff && c.checkedAt !== today);

const combined = [...kept, ...newChecks];

const header = `import type { PriceCheck } from "../types";

// Generated by \`npm run record-prices\` (scripts/record-price-check.ts) — run it after any
// manual price-verification pass over lib/data/parts.ts. Records today's price for every part
// currently in the catalog and prunes any entry older than 30 days, so this file is a rolling
// 30-day window of what's actually been checked, not a permanent price archive. Nothing here
// auto-updates on its own — pruning only happens the next time the script runs.
export const priceHistory: PriceCheck[] = [
`;
const body = combined
  .map((c) => `  { partId: "${c.partId}", price: ${c.price}, checkedAt: "${c.checkedAt}" },`)
  .join("\n");
const footer = "\n];\n";

writeFileSync(new URL("../lib/data/priceHistory.ts", import.meta.url), header + body + footer);
console.log(
  `Recorded ${newChecks.length} price checks for ${today}. History now has ${combined.length} entries (pruned anything older than 30 days).`
);
